
name: Issue Template
description: Template for issues
title: ""
labels: []
assignees: []
body:
  - type: textarea
    id: task
    attributes:
      label: Tasks
      description: "List of tasks"
      placeholder: "- Do XYZ\n- Do ABC"
    validations:
      required: false



