name: Deploy to GitHub Pages

on:
    push:
        branches:
            - main # Trigger the workflow on push to the main branch (or change to your default branch)
    workflow_dispatch:

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pages: write

        steps:
            - name: Checkout code
              uses: actions/checkout@v6.0.2

            - name: Set up Node.js
              uses: actions/setup-node@v6.3.0
              with:
                  node-version: '24.x'

            - name: Install dependencies
              run: |
                  npm install

            - name: Build the project
              run: |
                  npx expo export --platform web

            - name: Deploy to GitHub Pages
              run: |
                  git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
                  npx gh-pages --nojekyll -d dist -u "github-actions-bot <support+actions@github.com>"

                  SOURCE_SHA=${GITHUB_SHA}
                  SHORT_SHA=${SOURCE_SHA:0:7}
                  TAG="deploy-$(date -u +%Y%m%d)-${SHORT_SHA}"
                  git config user.name "github-actions-bot"
                  git config user.email "support+actions@github.com"

                  git tag -a "$TAG" "$SOURCE_SHA" -m "Deploy from ${SHORT_SHA}: $TAG"
                  git push origin "$TAG"
                  echo "deploy_tag=$TAG" >> $GITHUB_OUTPUT
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This is automatically provided by GitHub Actions

